// components/category-card.vue
<script setup>
   defineProps(['category'])
</script>

<style scoped>
   @import url("../assets/css/category.component.css");
</style>

<template>
  <NuxtLink :to= shop/category.id>
    <div class="subcategory" :style="{backgroundColor: '#' + category.color}">
      <div class="imgbox"><img :src="category.picture" /></div>
      <div class="textbox">
        <h3>{{ category.title }}</h3>
        <p>{{ category.desc }}</p>
      </div>
    </div></NuxtLink>
</template>

// components/category-card/category-card.component.ts
import { Component, OnInit } from '@angular/core';
import { Category } from 'src/shop-objects';

@Component({
  selector: 'app-category-card',
  templateUrl: './category-card.component.html',
  styleUrls: ['./category-card.component.css']
})
export class CategoryCardComponent implements OnInit {
  category: Category;

  constructor(category: Category) {
    this.category = category;
  }

  ngOnInit(): void {
  }

}

<a routerLink="shop/{{category.id}}">;
   <div class="subcategory" [ngStyle]="{color: '#' + category.color}">;
   <div class="imgbox"><img src= {{category.picture}} ></div>;
   <div class="textbox"><h3> {{category.title}}</h3>;
   <p>{{category.desc}}</p></div>;
</div></a>;
